name: bloodbank_nearby
description: A new Flutter project that follows with principles of Clean Architecture and has dummy RestAPI call.

publish_to: 'none' 





version: 1.0.0+1

environment:
  sdk: ">=2.17.0-225.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  lottie: ^1.2.2
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  dartz: ^0.10.1
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
   - assets/
  
  
  
  

  
  




  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
